fix/multiframe wadorui
cornerstonejs/cornerstone3D pull request #667
Opened 2023-06-23 00:40 UTC by sedghi

- fix multiframe index problem
- fix non scaled pt window level lazyniess
- build api
- apply review comments
- fix(PlanarFreehandROITool): trigger event after recalculation of stats (#665)
- chore(release): publish [skip ci]
- fix(multiframe): use portion of array buffer to send to webworker
- fix the place to put the options

### Context

### Changes & Results

### Testing

### Checklist

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

- [] I have run the `yarn build:update-api` to update the API documentation, and have
  committed the changes to this PR. (Read more here https://www.cornerstonejs.org/docs/contribute/update-api)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] "OS: 
- [] "Node version: 
- [] "Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

2023-07-11 01:04 UTC, wayfarer3130 requested changes
Just add the check for # of fragments / # of frames.   Might want to add that in a unit test so there is an obvious spot to add new tests to actually handle mismatches between # of frames  and fragments.

2023-10-18 12:39 UTC, jbocce reviewed
The changes look good. Perhaps address @wayfarer3130's comment. I tried restarting the Netlify build for the preview, but it failed again. If we can fix that too then I can give it a quick test. Thanks.

2023-10-20 13:38 UTC, jbocce commented on packages/core/src/init.ts
> +console.debug("core: link: init: 7DF8FBDE-F3DB-4B91-83DC-A47AE03BDD73");
Do we need this?

2023-10-20 13:39 UTC, jbocce commented on packages/dicomImageLoader/src/imageLoader/registerLoaders.ts
> +console.debug("dicom loader: link: init: 7DF8FBDE-F3DB-4B91-83DC-A47AE03BDD73");
Do we still want/need this?

2023-10-20 14:03 UTC, jbocce approved these changes
Thanks for the testing notes. I checked all of the various associated issues. Looks great!

2023-10-20 14:08 UTC, merged